export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  category: 'Dog Food' | 'Cat Toys' | 'Grooming' | 'Accessories' | 'Health & Wellness';
  rating: number;
  reviews: number;
  image: string;
  stockStatus: 'In Stock' | 'Low Stock' | 'Out of Stock';
  isFeatured?: boolean;
}

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Premium Salmon Kibble',
    description: 'Grain-free high-protein salmon and sweet potato recipe for adult dogs. Supports healthy skin and coat.',
    price: 54.99,
    category: 'Dog Food',
    rating: 4.8,
    reviews: 124,
    image: 'https://images.unsplash.com/photo-1544436484-67da678294e5?q=80&w=800&auto=format&fit=crop',
    stockStatus: 'In Stock',
    isFeatured: true,
  },
  {
    id: '2',
    name: 'Interactive Feather Wand',
    description: 'Keep your cat engaged for hours with this retractable feather wand. Includes 3 replaceable feather heads.',
    price: 12.50,
    category: 'Cat Toys',
    rating: 4.5,
    reviews: 89,
    image: 'https://images.unsplash.com/photo-1548546738-8509cb246ed3?q=80&w=800&auto=format&fit=crop',
    stockStatus: 'In Stock',
    isFeatured: true,
  },
  {
    id: '3',
    name: 'Self-Cleaning Slicker Brush',
    description: 'Professional grooming brush for long-haired pets. One-click hair removal makes cleaning effortless.',
    price: 18.99,
    category: 'Grooming',
    rating: 4.9,
    reviews: 342,
    image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?q=80&w=800&auto=format&fit=crop',
    stockStatus: 'In Stock',
    isFeatured: true,
  },
  {
    id: '4',
    name: 'Leather Padded Collar',
    description: 'Handcrafted genuine leather collar with soft interior padding for maximum comfort and durability.',
    price: 29.00,
    category: 'Accessories',
    rating: 4.7,
    reviews: 56,
    image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?q=80&w=800&auto=format&fit=crop',
    stockStatus: 'In Stock',
    isFeatured: false,
  },
  {
    id: '5',
    name: 'Joint Support Supplements',
    description: 'Glucosamine and Chondroitin soft chews to support hip and joint health in senior dogs.',
    price: 35.50,
    category: 'Health & Wellness',
    rating: 4.6,
    reviews: 112,
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=800&auto=format&fit=crop',
    stockStatus: 'Low Stock',
    isFeatured: true,
  },
  {
    id: '6',
    name: 'Tuna & Pumpkin Wet Food',
    description: 'Pack of 12 grain-free wet food cans for cats. High moisture content for urinary tract health.',
    price: 22.99,
    category: 'Dog Food', // Actually for cats but categorizing for variety
    rating: 4.4,
    reviews: 67,
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?q=80&w=800&auto=format&fit=crop',
    stockStatus: 'In Stock',
    isFeatured: false,
  },
  {
    id: '7',
    name: 'Ultra-Soft Orthopedic Bed',
    description: 'Memory foam pet bed with a washable cover. Perfect for pets with arthritis or muscle pain.',
    price: 89.99,
    category: 'Accessories',
    rating: 5.0,
    reviews: 215,
    image: 'https://images.unsplash.com/photo-1541599540903-21b157ac586f?q=80&w=800&auto=format&fit=crop',
    stockStatus: 'In Stock',
    isFeatured: true,
  },
  {
    id: '8',
    name: 'Organic Puppy Shampoo',
    description: 'Tear-free, hypoallergenic formula with aloe vera and chamomile for sensitive puppy skin.',
    price: 14.99,
    category: 'Grooming',
    rating: 4.8,
    reviews: 94,
    image: 'https://images.unsplash.com/photo-1583511655826-05700d52f4d9?q=80&w=800&auto=format&fit=crop',
    stockStatus: 'In Stock',
    isFeatured: false,
  },
  {
    id: '9',
    name: 'Catnip Filled Fish Toy',
    description: 'Double-sewn canvas toy filled with premium Canadian catnip. Stimulates natural hunting instincts.',
    price: 8.50,
    category: 'Cat Toys',
    rating: 4.7,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?q=80&w=800&auto=format&fit=crop',
    stockStatus: 'In Stock',
    isFeatured: false,
  },
  {
    id: '10',
    name: 'Calming Diffuser Kit',
    description: 'Pheromone diffuser to reduce stress and anxiety in multicat households. Covers up to 700 sq ft.',
    price: 42.00,
    category: 'Health & Wellness',
    rating: 4.3,
    reviews: 78,
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?q=80&w=800&auto=format&fit=crop',
    stockStatus: 'Low Stock',
    isFeatured: false,
  },
  {
    id: '11',
    name: 'Tough Chew Bone',
    description: 'Natural rubber bone designed for aggressive chewers. Promoting dental hygiene through play.',
    price: 15.99,
    category: 'Dog Food', // Categorizing under food/toys mixed
    rating: 4.6,
    reviews: 203,
    image: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?q=80&w=800&auto=format&fit=crop',
    stockStatus: 'In Stock',
    isFeatured: false,
  },
  {
    id: '12',
    name: 'Reflective Safety Vest',
    description: 'High-visibility vest for late-night walks. Water-resistant and adjustable straps.',
    price: 24.50,
    category: 'Accessories',
    rating: 4.9,
    reviews: 45,
    image: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?q=80&w=800&auto=format&fit=crop',
    stockStatus: 'In Stock',
    isFeatured: false,
  },
];
